[build-system]
requires = [
    "setuptools>=51"
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
skip = "pp*"

[tool.ruff]
line-length = 88 # same as black

[tool.ruff.lint]
extend-select = [
  "I",   # isort
  "PGH", # pygrep-hooks
  "RUF", # Ruff-specific
  "UP",  # pyupgrade
]