name: Build Documentation
on:
  push:
    branches:
      - master
  workflow_dispatch: null
permissions:
  contents: write
concurrency:
  group: docs-deploy
  cancel-in-progress: true
env:
  PYTHON_VERSION: "3.11"
  DOCS_OUTPUT_DIR: docs/build/html
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install doc build deps
        run: >
          python -m pip install -U pip

          # Adjust if you use a different requirements file

          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

          # Fallbacks if not using a requirements file (optional)

          python - <<'PY'

          import importlib, sys

          missing = [m for m in ("sphinx",) if not importlib.util.find_spec(m)]

          if missing:
              print("Installing:", missing)
              import subprocess; subprocess.check_call([sys.executable, "-m", "pip", "install", *missing])
          PY
      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable
          install-chromedriver: true
      - name: Build documentation (make html)
        run: make -C docs html
      - name: Publish HTML to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{ env.DOCS_OUTPUT_DIR }}
          force_orphan: true
          commit_message: "Docs: ${GITHUB_SHA::7}"
